public class de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally extends java.lang.Object
{

    public void <init>()
    {
        de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally this;

        nop;

        this := @this: de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally;

        specialinvoke this.<java.lang.Object: void <init>()>();

        return;
    }

    private static void tryCatchExample1()
    {
        java.io.PrintStream $stack2, $stack4;
        java.lang.NoSuchMethodException $stack1;
        java.lang.NoSuchFieldException $stack3;
        java.lang.String varReplacer52, varReplacer53, varReplacer54, varReplacer55;

     label1:
        nop;

        varReplacer53 = "Ranjith";

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void checkValid1(java.lang.String)>(varReplacer53);

        varReplacer55 = "ranj345n";

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void checkValid2(java.lang.String)>(varReplacer55);

     label2:
        goto label5;

     label3:
        $stack3 := @caughtexception;

        $stack4 = <java.lang.System: java.io.PrintStream out>;

        varReplacer54 = "Something went wrong in tryCatchExample1 (NoSuchFieldException)";

        virtualinvoke $stack4.<java.io.PrintStream: void println(java.lang.String)>(varReplacer54);

        goto label5;

     label4:
        $stack1 := @caughtexception;

        $stack2 = <java.lang.System: java.io.PrintStream out>;

        varReplacer52 = "Something went wrong in tryCatchExample1 (NoSuchMethodException)";

        virtualinvoke $stack2.<java.io.PrintStream: void println(java.lang.String)>(varReplacer52);

     label5:
        return;

        catch java.lang.NoSuchFieldException from label1 to label2 with label3;
        catch java.lang.NoSuchMethodException from label1 to label2 with label4;
    }

    private static void tryCatchExample2()
    {
        java.io.PrintStream $stack2;
        java.lang.NoSuchFieldException $stack1;
        java.lang.String varReplacer56, varReplacer57, varReplacer58;

     label1:
        nop;

        varReplacer58 = "Ranjith";

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void checkValid1(java.lang.String)>(varReplacer58);

        varReplacer56 = "ranj345n";

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void checkValid1(java.lang.String)>(varReplacer56);

     label2:
        goto label4;

     label3:
        $stack1 := @caughtexception;

        $stack2 = <java.lang.System: java.io.PrintStream out>;

        varReplacer57 = "Something went wrong in tryCatchExample2 (NoSuchFieldException)";

        virtualinvoke $stack2.<java.io.PrintStream: void println(java.lang.String)>(varReplacer57);

     label4:
        return;

        catch java.lang.NoSuchFieldException from label1 to label2 with label3;
    }

    private static void tryCatchExample3()
    {
        java.lang.Throwable $stack3;
        java.lang.NoSuchMethodException $stack5;
        java.lang.NoSuchFieldException $stack8;
        java.lang.String varReplacer59, varReplacer60, varReplacer61, varReplacer62, varReplacer63, varReplacer64, varReplacer65, varReplacer66;
        java.io.PrintStream $stack2, $stack4, $stack6, $stack7, $stack9, $stack10;

     label1:
        nop;

        varReplacer64 = "Ranjith";

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void checkValid1(java.lang.String)>(varReplacer64);

        varReplacer59 = "ranj345n";

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void checkValid2(java.lang.String)>(varReplacer59);

     label2:
        $stack2 = <java.lang.System: java.io.PrintStream out>;

        varReplacer66 = "Finally executed in tryCatchExample3";

        virtualinvoke $stack2.<java.io.PrintStream: void println(java.lang.String)>(varReplacer66);

        goto label8;

     label3:
        $stack8 := @caughtexception;

        $stack9 = <java.lang.System: java.io.PrintStream out>;

        varReplacer62 = "Something went wrong in tryCatchExample3 (NoSuchFieldException)";

        virtualinvoke $stack9.<java.io.PrintStream: void println(java.lang.String)>(varReplacer62);

     label4:
        $stack10 = <java.lang.System: java.io.PrintStream out>;

        varReplacer60 = "Finally executed in tryCatchExample3";

        virtualinvoke $stack10.<java.io.PrintStream: void println(java.lang.String)>(varReplacer60);

        goto label8;

     label5:
        $stack5 := @caughtexception;

        $stack6 = <java.lang.System: java.io.PrintStream out>;

        varReplacer61 = "Something went wrong in tryCatchExample3 (NoSuchMethodException)";

        virtualinvoke $stack6.<java.io.PrintStream: void println(java.lang.String)>(varReplacer61);

     label6:
        $stack7 = <java.lang.System: java.io.PrintStream out>;

        varReplacer63 = "Finally executed in tryCatchExample3";

        virtualinvoke $stack7.<java.io.PrintStream: void println(java.lang.String)>(varReplacer63);

        goto label8;

     label7:
        $stack3 := @caughtexception;

        $stack4 = <java.lang.System: java.io.PrintStream out>;

        varReplacer65 = "Finally executed in tryCatchExample3";

        virtualinvoke $stack4.<java.io.PrintStream: void println(java.lang.String)>(varReplacer65);

        throw $stack3;

     label8:
        return;

        catch java.lang.NoSuchFieldException from label1 to label2 with label3;
        catch java.lang.NoSuchMethodException from label1 to label2 with label5;
        catch java.lang.Throwable from label1 to label2 with label7;
        catch java.lang.Throwable from label3 to label4 with label7;
        catch java.lang.Throwable from label5 to label6 with label7;
    }

    private static void checkValid1(java.lang.String) throws java.lang.NoSuchFieldException
    {
        java.lang.NoSuchFieldException $stack2;
        java.lang.String name, varReplacer67, varReplacer68;
        boolean $stack1;

        nop;

        name := @parameter0: java.lang.String;

        varReplacer67 = ".*\\d.*";

        $stack1 = virtualinvoke name.<java.lang.String: boolean matches(java.lang.String)>(varReplacer67);

        if $stack1 == 0 goto label1;

        nop;

        $stack2 = new java.lang.NoSuchFieldException;

        varReplacer68 = "Invalid name";

        specialinvoke $stack2.<java.lang.NoSuchFieldException: void <init>(java.lang.String)>(varReplacer68);

        throw $stack2;

     label1:
        nop;

        return;
    }

    private static void checkValid2(java.lang.String) throws java.lang.NoSuchMethodException
    {
        java.lang.NoSuchMethodException $stack2;
        java.lang.String name, varReplacer69, varReplacer70;
        boolean $stack1;

        nop;

        name := @parameter0: java.lang.String;

        varReplacer70 = ".*\\d.*";

        $stack1 = virtualinvoke name.<java.lang.String: boolean matches(java.lang.String)>(varReplacer70);

        if $stack1 == 0 goto label1;

        nop;

        $stack2 = new java.lang.NoSuchMethodException;

        varReplacer69 = "Invalid name";

        specialinvoke $stack2.<java.lang.NoSuchMethodException: void <init>(java.lang.String)>(varReplacer69);

        throw $stack2;

     label1:
        nop;

        return;
    }

    public static void main(java.lang.String[])
    {
        java.lang.String[] args;

        nop;

        args := @parameter0: java.lang.String[];

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void tryCatchExample1()>();

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void tryCatchExample2()>();

        staticinvoke <de.fraunhofer.iem.basics.controlFlow.exceptions.JavaTryCatchFinally: void tryCatchExample3()>();

        return;
    }
}
